### ISSUE TITLE
使用yarn install安装包，运行时抛出如下异常

### ISSUE THREAD

**Issue by wingsheep** [dreamqyq/coast-ui-vue3#7]
使用yarn install安装包，运行时抛出如下异常，使用npm安装使用正常
![image](https://user-images.githubusercontent.com/26684771/124091350-5320d480-da88-11eb-91cf-0e2f31e037bf.png)

具体遇到的问题和下面这个issue评论是一样的
[https://github.com/vuejs/vue-next/issues/2064#issuecomment-733924405](https://github.com/vuejs/vue-next/issues/2064#issuecomment-733924405)

我查到的相关的issue，试了其中的配置方法，无效🙃, 我搜索npm中使用vite  + vue3 写的组件部分也有相同的问题，望周知！🇨🇳🇨🇳🇨🇳
[https://github.com/vuejs/vue-next/issues/2064](https://github.com/vuejs/vue-next/issues/2064)
[https://github.com/vuejs/vue-next/issues/3854](https://github.com/vuejs/vue-next/issues/3854)

**Comment by dreamqyq** [comment]
谢谢反馈

**Comment by aarlandclaudel** [comment]
Having the same problem when importing my component from storybook
Any solution plz ???

**Comment by dreamqyq** [comment]
经测试，2021年7月18日发布的0.4.1版本已无此问题
